results_dir: C:\Users\rocha\Desktop\USMA 2026
model_path: C:/Users/rocha/Desktop/SAP2000 test/test.sdb
case_name: NLTH_BATCH
use_ping_pong: false
ping_pong_cases:
- NLTH_A
- NLTH_B
initial_gravity_case: NL DL+0.25LL
checkpoint_every: 10
clear_results_after_edp: true
energy_link: '4'
enable_link_energy: false
energy_component: U1_P
energy_point_elm: I-End
energy_mode: signed
output_time_step: 0.01
output_units: cm
accel_in_g: true
overwrite_db: true
nlth_case:
  apply_parameters: false
  p_delta: true
  initial_case: NL DL+0.25LL
  damping:
    method: SetDampProportional
    args:
    - 1
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  time_integration:
    method: newmark
    alpha: 0.0
    beta: 0.25
    gamma: 0.5
    theta: 0.0
  nonlinear_parameters:
    dt_max_factor: 1.0
    dt_min_factor: 0.2
    max_iter_cs: 6
    max_iter_nr: 20
    tol_conv_d: 0.001
    use_event_stepping: true
    tol_event_d: 0.005
    max_line_search_per_iter: 3
    tol_line_search: 0.8
    line_search_step_fact: 2.0
  initial_conditions:
    method: ''
    args: []
nodes:
- name: BASE
  joint: '13'
  z: 0.0
- name: L01
  joint: '14'
  z: 300.0
- name: L02
  joint: '15'
  z: 600.0
- name: ROOF
  joint: '32'
  z: 900.0
